"""Agregar campos email y sector

Revision ID: 07a941bdf0ae
Revises: 667fdab94e2a
Create Date: 2024-12-20 15:11:24.920789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a941bdf0ae'
down_revision = '667fdab94e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.drop_column('sector')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
