"""Agregar campo it5_retroalimentacion

Revision ID: 667fdab94e2a
Revises: 
Create Date: 2024-12-12 10:15:59.785408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '667fdab94e2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('it5_retroalimentacion', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('it6_mecanismos_articulacion', sa.String(length=1), nullable=True))
        batch_op.alter_column('p1_identificacion_amenazas',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('p2_identificacion_vulnerabilidades',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('p3_analisis_riesgos',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('p4_valoracion_riesgos',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('p5_reduccion_riesgos',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('p6_monitoreo_revision',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('p7_seguimiento_estrategias',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('p8_comunicacion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt1_adopcion_certificaciones',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt2_regulaciones_nacionales',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt3_plan_gestion_riesgo',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt4_politica_gestion_riesgo',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt5_politica_seguridad',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt6_sistema_sarlaft',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt7_memoria_emergencias',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt8_planes_emergencia',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('pt9_seguros_polizas',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('eq1_control_acceso',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('eq2_controles_seguridad',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('eq3_controles_ciberseguridad',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('eq4_redes_deteccion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('eq5_brigadas_respuesta',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('eq6_formacion_capacitacion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('it1_transversalizacion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('it2_protocolos_comunicacion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('it3_planes_ayuda',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('or1_area_gestion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('or2_presupuesto',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('or3_personal_dedicacion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('or4_proyectos_gestion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('or5_inclusion_gestion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.drop_column('it5_mecanismos_articulacion')
        batch_op.drop_column('it4_retroalimentacion')
        batch_op.drop_column('it6_integracion_procesos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('it6_integracion_procesos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('it4_retroalimentacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('it5_mecanismos_articulacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.alter_column('or5_inclusion_gestion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('or4_proyectos_gestion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('or3_personal_dedicacion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('or2_presupuesto',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('or1_area_gestion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('it3_planes_ayuda',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('it2_protocolos_comunicacion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('it1_transversalizacion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('eq6_formacion_capacitacion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('eq5_brigadas_respuesta',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('eq4_redes_deteccion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('eq3_controles_ciberseguridad',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('eq2_controles_seguridad',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('eq1_control_acceso',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt9_seguros_polizas',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt8_planes_emergencia',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt7_memoria_emergencias',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt6_sistema_sarlaft',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt5_politica_seguridad',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt4_politica_gestion_riesgo',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt3_plan_gestion_riesgo',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt2_regulaciones_nacionales',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('pt1_adopcion_certificaciones',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('p8_comunicacion',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('p7_seguimiento_estrategias',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('p6_monitoreo_revision',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('p5_reduccion_riesgos',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('p4_valoracion_riesgos',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('p3_analisis_riesgos',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('p2_identificacion_vulnerabilidades',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('p1_identificacion_amenazas',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.drop_column('it6_mecanismos_articulacion')
        batch_op.drop_column('it5_retroalimentacion')

    # ### end Alembic commands ###
